### PR TITLE
migrate Printable Area function; bump jsPDF version

### PR DESCRIPTION
**Pull request by smellman**
## Description

Migrate Printable Area function from mapbox-gl-export.
bump jsPDF version.

## Type of Pull Request

- [x] Adding a feature
- [ ] Fixing a bug
- [x] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No lint errors after `npm run lint`
- [x] Make sure all the exsiting features working well

### CODE REVIEW

**Comment by smellman** [comment]
The PR is take diff between both lib directories.
OK for merge other PRs.

**Comment by smellman** [comment]
I merged mapbox-gl-export#20 and #25 but I missed fixes css in #20. so I merged it.

**Comment by smellman** [comment]
How about github template?

**Comment by smellman** [comment]
I merged .github directory and package.json from mapbox-gl-export.

**Comment by JinIgarashi** [comment]
@smellman CI failed.

```
 TS2339: Property 'msSaveBlob' does not exist on type 'Navigator'.
```

The below code stopped CI run.

https://github.com/smellman/maplibre-gl-export/blob/0c54a6119c51009d8cc841606903408da844c601/lib/map-generator.ts#L243-L245

This code is for IE11, so maybe we can remove this part of code. What do you think? I think Mapbox and Maplibre are now not supporting IE11?

**Pull request merged**
